# Generated by Django 5.0.2 on 2024-02-17 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_favorite", "0001_initial"),
        ("app_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_product.product"
            ),
        ),
    ]
