# Generated by Django 4.2.11 on 2024-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0002_remove_history_author_history_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
