# Generated by Django 4.2.11 on 2024-03-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0003_history_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="location",
        ),
    ]
