# Generated by Django 4.2.11 on 2024-03-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0004_remove_history_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("1", "Оплачено"), ("2", "На проверке"), ("3", "Доставлено")],
            ),
        ),
    ]
