# Generated by Django 4.2.11 on 2024-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0006_alter_history_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
