# Generated by Django 4.2.11 on 2024-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0007_history_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="deliver",
        ),
        migrations.AddField(
            model_name="history",
            name="location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="types",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Deliver",
        ),
    ]
