version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    # environment:
    #   - DJANGO_SETTINGS_MODULE=config.settings.base
    environment:
      - VIRTUAL_HOST=aitim-trade-backend.net
      - LETSENCRYPT_HOST=aitim-trade-backend.net
      
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db


  nginx:
     build:
       context: .
       dockerfile: nginx/Dockerfile
     ports:
       - "80:80"
     volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
     depends_on:
       - web

volumes:
  db_data:
  static_volume:
  media_volume: