version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    # ports:
    #   - 8000:8000
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat
      # - pgbouncer

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    


  # pgbouncer:
  #   image: edoburu/pgbouncer:latest
  #   build: .
  #     # dockerfile: pgbouncer/Dockerfile
  #   volumes:
  #     - ./etc/pgbouncer:/etc/pgbouncer:ro
  #   environment:
  #     - PGBOUNCER_INI=pgbouncer.ini
  #     - DATABASES_HOST=db
  #     - DATABASES_PORT=5432
  #     - DATABASES_USER=postgres
  #     - DATABASES_PASSWORD=123
  #     - ADMIN_USERS=postgres
  #   ports:
  #     - "6432:6432"
  #   restart: always
    
  redis:
    image: "redis:alpine"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db

  


volumes:
  db_data:
  static_volume:
  media_volume: