# Generated by Django 5.0.2 on 2024-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_alter_customuser_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="code",
            field=models.CharField(blank=True, default=1, max_length=6),
            preserve_default=False,
        ),
    ]
