# Generated by Django 4.2.11 on 2024-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_product", "0002_product_is_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.ManyToManyField(to="app_product.product")),
            ],
        ),
    ]
