# Generated by Django 4.2.11 on 2024-03-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0002_product_is_favorite"),
        ("app_collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Product", models.ManyToManyField(to="app_product.product")),
            ],
        ),
    ]
