# Generated by Django 4.2.11 on 2024-03-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_basket", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="basket",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Basket",
        ),
        migrations.DeleteModel(
            name="BasketItem",
        ),
    ]
