# Generated by Django 5.0.2 on 2024-02-17 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_basket", "0001_initial"),
        ("app_product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="app_basket.basket",
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_items",
                to="app_product.product",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(
                through="app_basket.BasketItem", to="app_product.product"
            ),
        ),
    ]
