# Generated by Django 5.0.2 on 2024-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='app_category/Category_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='app_category/SubCategory_images'),
            preserve_default=False,
        ),
    ]
