# Generated by Django 4.2.11 on 2024-03-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_category", "0002_alter_category_image_alter_subcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="text/"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(upload_to="text/"),
        ),
    ]
