# Generated by Django 5.0.2 on 2024-02-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colors", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sizes", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sizes"], name="app_product_sizes_277361_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("brand", models.CharField(max_length=255)),
                ("characteristics", models.TextField()),
                ("is_any", models.BooleanField(default=False)),
                ("discount", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "images1",
                    models.ImageField(
                        blank=True, null=True, upload_to="app_product/image/"
                    ),
                ),
                (
                    "images2",
                    models.ImageField(
                        blank=True, null=True, upload_to="app_product/image/"
                    ),
                ),
                (
                    "images3",
                    models.ImageField(
                        blank=True, null=True, upload_to="app_product/image/"
                    ),
                ),
                ("color", models.ManyToManyField(to="app_product.color")),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_category.subcategory",
                    ),
                ),
                ("size", models.ManyToManyField(to="app_product.size")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="app_product_title_8ca7b9_idx"),
                    models.Index(fields=["brand"], name="app_product_brand_e5e704_idx"),
                ],
            },
        ),
    ]
