# Generated by Django 5.0.2 on 2024-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colors", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("brand", models.CharField(max_length=255)),
                ("characteristics", models.TextField()),
                ("is_any", models.BooleanField(default=False)),
                (
                    "images1",
                    models.ImageField(
                        blank=True, null=True, upload_to="app_product/image/"
                    ),
                ),
                (
                    "images2",
                    models.ImageField(
                        blank=True, null=True, upload_to="app_product/image/"
                    ),
                ),
                (
                    "images3",
                    models.ImageField(
                        blank=True, null=True, upload_to="app_product/image/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sizes", models.CharField(max_length=255)),
            ],
        ),
    ]
