# Generated by Django 5.0.2 on 2024-03-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
