# Generated by Django 5.0.2 on 2024-02-17 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_category", "0001_initial"),
        ("app_product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(to="app_product.color"),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_category.subcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="size",
            index=models.Index(fields=["sizes"], name="app_product_sizes_277361_idx"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(to="app_product.size"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["title"], name="app_product_title_8ca7b9_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="app_product_brand_e5e704_idx"),
        ),
    ]
