# Generated by Django 5.0.2 on 2024-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(upload_to='app_product/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images3',
            field=models.ImageField(upload_to='app_product/image/'),
        ),
    ]
