# Generated by Django 5.0.2 on 2024-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_alter_product_images2_alter_product_images3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images1',
            field=models.ImageField(blank=True, null=True, upload_to='app_product/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='app_product/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='app_product/image/'),
        ),
    ]
