# Generated by Django 5.0.2 on 2024-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0002_product_is_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacteristikTopik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="characteristics",
        ),
        migrations.AddField(
            model_name="product",
            name="characteristics",
            field=models.ManyToManyField(to="app_product.characteristiktopik"),
        ),
    ]
