# Generated by Django 5.0.2 on 2024-03-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0003_alter_product_images1_alter_product_images2_and_more"),
        (
            "app_product",
            "0003_characteristiktopik_remove_product_characteristics_and_more",
        ),
    ]

    operations = []
