# Generated by Django 4.2.11 on 2024-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0003_alter_product_images1_alter_product_images2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
