# Generated by Django 5.0.2 on 2024-02-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0003_product_app_product_title_8ca7b9_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="app_product_title_8ca7b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="app_product_brand_e5e704_idx",
        ),
    ]
