# Generated by Django 5.0.2 on 2024-02-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_category", "0001_initial"),
        ("app_product", "0004_remove_product_app_product_title_8ca7b9_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["title"], name="app_product_title_8ca7b9_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="app_product_brand_e5e704_idx"),
        ),
    ]
