# Generated by Django 5.0.2 on 2024-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0005_product_app_product_title_8ca7b9_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
