# Generated by Django 5.0.2 on 2024-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='app_product.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='app_product.size'),
        ),
    ]
