# Generated by Django 5.0.2 on 2024-02-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_remove_product_colors_product_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='size',
        ),
    ]
