# Generated by Django 5.0.2 on 2024-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_product", "0006_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
