# Generated by Django 5.0.2 on 2024-02-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_rename_sizes_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='sizes',
        ),
    ]
